# Generated by Django 4.2 on 2024-03-18 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disaster_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CERT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_text', models.TextField()),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Disaster_management_app.community')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, default=0.0, null=True)),
                ('humidity', models.FloatField(blank=True, default=0.0, null=True)),
                ('dewpoint', models.FloatField(blank=True, default=0.0, null=True)),
                ('land_surface_temperature', models.FloatField(blank=True, default=0.0, null=True)),
                ('low_atmospheric_pressure', models.FloatField(blank=True, default=0.0, null=True)),
                ('streamflow_river_discharge', models.FloatField(blank=True, default=0.0, null=True)),
                ('unhealthy_vegetation', models.FloatField(blank=True, default=0.0, null=True)),
                ('smoking_indoors', models.FloatField(blank=True, default=0.0, null=True)),
                ('smoke_detectors', models.FloatField(blank=True, default=0.0, null=True)),
                ('fire_extinguishers', models.FloatField(blank=True, default=0.0, null=True)),
                ('open_flame', models.FloatField(blank=True, default=0.0, null=True)),
                ('high_transmission_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('high_hospitalized_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('high_number_of_cases', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamproject',
            name='members',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploader',
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(default='DefaultLocation', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='TeamProject',
        ),
    ]
